//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hashi.Gui.Language {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hashi.Gui.Language.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abort ähnelt.
        /// </summary>
        public static string Abort {
            get {
                return ResourceManager.GetString("Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Accelerometers ähnelt.
        /// </summary>
        public static string Acc {
            get {
                return ResourceManager.GetString("Acc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Terminal name ähnelt.
        /// </summary>
        public static string Acc_Address {
            get {
                return ResourceManager.GetString("Acc_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Limit Max Value ähnelt.
        /// </summary>
        public static string Acc_MaxLimit {
            get {
                return ResourceManager.GetString("Acc_MaxLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Measurement length [hh:mm:ss] ähnelt.
        /// </summary>
        public static string Acc_MeasurementLength {
            get {
                return ResourceManager.GetString("Acc_MeasurementLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Limit Min Value ähnelt.
        /// </summary>
        public static string Acc_MinLimit {
            get {
                return ResourceManager.GetString("Acc_MinLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Accelerometer name ähnelt.
        /// </summary>
        public static string Acc_Name {
            get {
                return ResourceManager.GetString("Acc_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Offset ähnelt.
        /// </summary>
        public static string Acc_Offset {
            get {
                return ResourceManager.GetString("Acc_Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Accelerometers overview ähnelt.
        /// </summary>
        public static string Acc_Overview {
            get {
                return ResourceManager.GetString("Acc_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sampling Rate [kHz] ähnelt.
        /// </summary>
        public static string Acc_SamplingRate {
            get {
                return ResourceManager.GetString("Acc_SamplingRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scale m/s²/V ähnelt.
        /// </summary>
        public static string Acc_Scale {
            get {
                return ResourceManager.GetString("Acc_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unit ähnelt.
        /// </summary>
        public static string Acc_Unit {
            get {
                return ResourceManager.GetString("Acc_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die X-Axis name ähnelt.
        /// </summary>
        public static string Acc_XAxis {
            get {
                return ResourceManager.GetString("Acc_XAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Y-Axis name ähnelt.
        /// </summary>
        public static string Acc_YAxis {
            get {
                return ResourceManager.GetString("Acc_YAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Terminal name ähnelt.
        /// </summary>
        public static string AccTable_Address {
            get {
                return ResourceManager.GetString("AccTable_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Limit Max ähnelt.
        /// </summary>
        public static string AccTable_MaxLimit {
            get {
                return ResourceManager.GetString("AccTable_MaxLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Measurement Time ähnelt.
        /// </summary>
        public static string AccTable_MeasurementLength {
            get {
                return ResourceManager.GetString("AccTable_MeasurementLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Limit Min ähnelt.
        /// </summary>
        public static string AccTable_MinLimit {
            get {
                return ResourceManager.GetString("AccTable_MinLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Accelerometer name ähnelt.
        /// </summary>
        public static string AccTable_Name {
            get {
                return ResourceManager.GetString("AccTable_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Offset ähnelt.
        /// </summary>
        public static string AccTable_Offset {
            get {
                return ResourceManager.GetString("AccTable_Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sampling ähnelt.
        /// </summary>
        public static string AccTable_Sampling {
            get {
                return ResourceManager.GetString("AccTable_Sampling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scale ähnelt.
        /// </summary>
        public static string AccTable_Scale {
            get {
                return ResourceManager.GetString("AccTable_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unit ähnelt.
        /// </summary>
        public static string AccTable_Unit {
            get {
                return ResourceManager.GetString("AccTable_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die X-Axis ähnelt.
        /// </summary>
        public static string AccTable_XAxis {
            get {
                return ResourceManager.GetString("AccTable_XAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Y-Axis ähnelt.
        /// </summary>
        public static string AccTable_YAxis {
            get {
                return ResourceManager.GetString("AccTable_YAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This entry already exists in database. ähnelt.
        /// </summary>
        public static string AddEntry_ErrorExists {
            get {
                return ResourceManager.GetString("AddEntry_ErrorExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a text. ähnelt.
        /// </summary>
        public static string AddEntry_ErrorMissingText {
            get {
                return ResourceManager.GetString("AddEntry_ErrorMissingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entry to add: ähnelt.
        /// </summary>
        public static string AddEntry_Text {
            get {
                return ResourceManager.GetString("AddEntry_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add New Entry ähnelt.
        /// </summary>
        public static string AddEntry_Title {
            get {
                return ResourceManager.GetString("AddEntry_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PLC Constants ähnelt.
        /// </summary>
        public static string Constants {
            get {
                return ResourceManager.GetString("Constants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Accelerometers ähnelt.
        /// </summary>
        public static string Constants_Acc {
            get {
                return ResourceManager.GetString("Constants_Acc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sampling rate of sensors [kS] ähnelt.
        /// </summary>
        public static string Constants_Acc_SamplingRate {
            get {
                return ResourceManager.GetString("Constants_Acc_SamplingRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scale range of acceleration sensors ähnelt.
        /// </summary>
        public static string Constants_Acc_ScaleRange {
            get {
                return ResourceManager.GetString("Constants_Acc_ScaleRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Total samples collected for each acceleration sensor when testing sensors ähnelt.
        /// </summary>
        public static string Constants_Acc_TotalSamples {
            get {
                return ResourceManager.GetString("Constants_Acc_TotalSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Oversampling rate ähnelt.
        /// </summary>
        public static string Constants_All_OversamplingRate {
            get {
                return ResourceManager.GetString("Constants_All_OversamplingRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number of presamples before sensor values exceed threshold ähnelt.
        /// </summary>
        public static string Constants_All_PreSamplingLength {
            get {
                return ResourceManager.GetString("Constants_All_PreSamplingLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All sensors ähnelt.
        /// </summary>
        public static string Constants_AllSensors {
            get {
                return ResourceManager.GetString("Constants_AllSensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rpms ähnelt.
        /// </summary>
        public static string Constants_Rpm {
            get {
                return ResourceManager.GetString("Constants_Rpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Total samples collected for each rpm sensor when testing sensors ähnelt.
        /// </summary>
        public static string Constants_Rpm_TotalSamples {
            get {
                return ResourceManager.GetString("Constants_Rpm_TotalSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Countdown ähnelt.
        /// </summary>
        public static string Countdown_Countdown {
            get {
                return ResourceManager.GetString("Countdown_Countdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Interval ähnelt.
        /// </summary>
        public static string Countdown_Intervall {
            get {
                return ResourceManager.GetString("Countdown_Intervall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next Measurement ähnelt.
        /// </summary>
        public static string Countdown_Time {
            get {
                return ResourceManager.GetString("Countdown_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Currently installed Version: ähnelt.
        /// </summary>
        public static string DotNet_Message {
            get {
                return ResourceManager.GetString("DotNet_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Installed .NET-Framework ähnelt.
        /// </summary>
        public static string DotNet_Title {
            get {
                return ResourceManager.GetString("DotNet_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Misc. Sensors ähnelt.
        /// </summary>
        public static string Dynamic {
            get {
                return ResourceManager.GetString("Dynamic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Terminal name ähnelt.
        /// </summary>
        public static string Dynamic_Address {
            get {
                return ResourceManager.GetString("Dynamic_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sensor name ähnelt.
        /// </summary>
        public static string Dynamic_Name {
            get {
                return ResourceManager.GetString("Dynamic_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Offset ähnelt.
        /// </summary>
        public static string Dynamic_Offset {
            get {
                return ResourceManager.GetString("Dynamic_Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scale ähnelt.
        /// </summary>
        public static string Dynamic_Scale {
            get {
                return ResourceManager.GetString("Dynamic_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die X-Axis ähnelt.
        /// </summary>
        public static string Dynamic_XAxis {
            get {
                return ResourceManager.GetString("Dynamic_XAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Y-Axis ähnelt.
        /// </summary>
        public static string Dynamic_YAxis {
            get {
                return ResourceManager.GetString("Dynamic_YAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clamp ähnelt.
        /// </summary>
        public static string DynamicTable_Address {
            get {
                return ResourceManager.GetString("DynamicTable_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sensor name ähnelt.
        /// </summary>
        public static string DynamicTable_Name {
            get {
                return ResourceManager.GetString("DynamicTable_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Offset ähnelt.
        /// </summary>
        public static string DynamicTable_Offset {
            get {
                return ResourceManager.GetString("DynamicTable_Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scale ähnelt.
        /// </summary>
        public static string DynamicTable_Scale {
            get {
                return ResourceManager.GetString("DynamicTable_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die X-Axis ähnelt.
        /// </summary>
        public static string DynamicTable_XAxis {
            get {
                return ResourceManager.GetString("DynamicTable_XAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Y-Axis ähnelt.
        /// </summary>
        public static string DynamicTable_YAxis {
            get {
                return ResourceManager.GetString("DynamicTable_YAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Input must be of type boolean ähnelt.
        /// </summary>
        public static string Error_Bool {
            get {
                return ResourceManager.GetString("Error_Bool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This type of value is not supported ähnelt.
        /// </summary>
        public static string Error_Default {
            get {
                return ResourceManager.GetString("Error_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Input must be of type double ähnelt.
        /// </summary>
        public static string Error_Double {
            get {
                return ResourceManager.GetString("Error_Double", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Input must be of type float ähnelt.
        /// </summary>
        public static string Error_Float {
            get {
                return ResourceManager.GetString("Error_Float", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a number with 7 digits or leave empty ähnelt.
        /// </summary>
        public static string Error_IEPE {
            get {
                return ResourceManager.GetString("Error_IEPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Input must be of type int ähnelt.
        /// </summary>
        public static string Error_Int32 {
            get {
                return ResourceManager.GetString("Error_Int32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Input must be of type int ähnelt.
        /// </summary>
        public static string Error_Int64 {
            get {
                return ResourceManager.GetString("Error_Int64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please type in a number between 0 and 255 ähnelt.
        /// </summary>
        public static string Error_IP {
            get {
                return ResourceManager.GetString("Error_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minimum standby time is 5min ähnelt.
        /// </summary>
        public static string Error_PLC_CommStandbyTime {
            get {
                return ResourceManager.GetString("Error_PLC_CommStandbyTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minimum value is 10 mins ähnelt.
        /// </summary>
        public static string Error_StandbyTime {
            get {
                return ResourceManager.GetString("Error_StandbyTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value cannot be converted to string ähnelt.
        /// </summary>
        public static string Error_String {
            get {
                return ResourceManager.GetString("Error_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version Info ähnelt.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Build Number: ähnelt.
        /// </summary>
        public static string Info_BuildNo {
            get {
                return ResourceManager.GetString("Info_BuildNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Major Version: ähnelt.
        /// </summary>
        public static string Info_Major {
            get {
                return ResourceManager.GetString("Info_Major", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minor_Version: ähnelt.
        /// </summary>
        public static string Info_Minor {
            get {
                return ResourceManager.GetString("Info_Minor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Revision Number: ähnelt.
        /// </summary>
        public static string Info_RevisionNo {
            get {
                return ResourceManager.GetString("Info_RevisionNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IP-Management ähnelt.
        /// </summary>
        public static string IP {
            get {
                return ResourceManager.GetString("IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Adapter name ähnelt.
        /// </summary>
        public static string IP_AdapterName {
            get {
                return ResourceManager.GetString("IP_AdapterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IP Address ähnelt.
        /// </summary>
        public static string IP_Address {
            get {
                return ResourceManager.GetString("IP_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do not change gateway ähnelt.
        /// </summary>
        public static string IP_DoNotChangeGateway {
            get {
                return ResourceManager.GetString("IP_DoNotChangeGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mask ähnelt.
        /// </summary>
        public static string IP_Mask {
            get {
                return ResourceManager.GetString("IP_Mask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IP-Type ähnelt.
        /// </summary>
        public static string IP_Type {
            get {
                return ResourceManager.GetString("IP_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log file content ähnelt.
        /// </summary>
        public static string Log_Name {
            get {
                return ResourceManager.GetString("Log_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Forgot password? ähnelt.
        /// </summary>
        public static string Login_Forgot_Password {
            get {
                return ResourceManager.GetString("Login_Forgot_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name: ähnelt.
        /// </summary>
        public static string Login_Name {
            get {
                return ResourceManager.GetString("Login_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password: ähnelt.
        /// </summary>
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set new Password ähnelt.
        /// </summary>
        public static string Login_SetNewPassword {
            get {
                return ResourceManager.GetString("Login_SetNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This computer is not licenced to use the CMS-Wind Tool. Please contact bha@cms-wind.de ähnelt.
        /// </summary>
        public static string MAC_LicensingMessage {
            get {
                return ResourceManager.GetString("MAC_LicensingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Missing Licence ähnelt.
        /// </summary>
        public static string MAC_LicensingTitle {
            get {
                return ResourceManager.GetString("MAC_LicensingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current role: ähnelt.
        /// </summary>
        public static string Main_CurrentRole {
            get {
                return ResourceManager.GetString("Main_CurrentRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Infopanel ähnelt.
        /// </summary>
        public static string Main_Infopanel {
            get {
                return ResourceManager.GetString("Main_Infopanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IP: ähnelt.
        /// </summary>
        public static string Main_IP {
            get {
                return ResourceManager.GetString("Main_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Test sensors ähnelt.
        /// </summary>
        public static string Main_KnockButton {
            get {
                return ResourceManager.GetString("Main_KnockButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start logging sensors ähnelt.
        /// </summary>
        public static string Main_LogButton {
            get {
                return ResourceManager.GetString("Main_LogButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login name: ähnelt.
        /// </summary>
        public static string Main_LoginName {
            get {
                return ResourceManager.GetString("Main_LoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login time: ähnelt.
        /// </summary>
        public static string Main_LoginTime {
            get {
                return ResourceManager.GetString("Main_LoginTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Currently logging sensor data... - Status: ähnelt.
        /// </summary>
        public static string Main_MeasureStatus {
            get {
                return ResourceManager.GetString("Main_MeasureStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Port: ähnelt.
        /// </summary>
        public static string Main_Port {
            get {
                return ResourceManager.GetString("Main_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        public static string MainMenu_About {
            get {
                return ResourceManager.GetString("MainMenu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Accelerometer Functionality Test ähnelt.
        /// </summary>
        public static string MainMenu_AccFunctionalityTest {
            get {
                return ResourceManager.GetString("MainMenu_AccFunctionalityTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Accelerometers Overview ähnelt.
        /// </summary>
        public static string MainMenu_AccOverview {
            get {
                return ResourceManager.GetString("MainMenu_AccOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Admin ähnelt.
        /// </summary>
        public static string MainMenu_Admin {
            get {
                return ResourceManager.GetString("MainMenu_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change Language ähnelt.
        /// </summary>
        public static string MainMenu_ChangeLanguage {
            get {
                return ResourceManager.GetString("MainMenu_ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PLC Constants ähnelt.
        /// </summary>
        public static string MainMenu_ConstantSettings {
            get {
                return ResourceManager.GetString("MainMenu_ConstantSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Display settings ähnelt.
        /// </summary>
        public static string MainMenu_DisplaySettings {
            get {
                return ResourceManager.GetString("MainMenu_DisplaySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Determine installed .NET framework version ähnelt.
        /// </summary>
        public static string MainMenu_DotNet {
            get {
                return ResourceManager.GetString("MainMenu_DotNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Misc. Sensors Overview ähnelt.
        /// </summary>
        public static string MainMenu_DynamicOverview {
            get {
                return ResourceManager.GetString("MainMenu_DynamicOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit Program ähnelt.
        /// </summary>
        public static string MainMenu_ExitProgram {
            get {
                return ResourceManager.GetString("MainMenu_ExitProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export Sensor Settings ähnelt.
        /// </summary>
        public static string MainMenu_ExportSettings {
            get {
                return ResourceManager.GetString("MainMenu_ExportSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import/Export ähnelt.
        /// </summary>
        public static string MainMenu_ImportExport {
            get {
                return ResourceManager.GetString("MainMenu_ImportExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import Sensor Settings ähnelt.
        /// </summary>
        public static string MainMenu_ImportSettings {
            get {
                return ResourceManager.GetString("MainMenu_ImportSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version Info ähnelt.
        /// </summary>
        public static string MainMenu_Info {
            get {
                return ResourceManager.GetString("MainMenu_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IP Management ähnelt.
        /// </summary>
        public static string MainMenu_IPManagement {
            get {
                return ResourceManager.GetString("MainMenu_IPManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die English ähnelt.
        /// </summary>
        public static string MainMenu_LanguageEnglish {
            get {
                return ResourceManager.GetString("MainMenu_LanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die German ähnelt.
        /// </summary>
        public static string MainMenu_LanguageGerman {
            get {
                return ResourceManager.GetString("MainMenu_LanguageGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NPT Time ähnelt.
        /// </summary>
        public static string MainMenu_NPTTime {
            get {
                return ResourceManager.GetString("MainMenu_NPTTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PLC Settings ähnelt.
        /// </summary>
        public static string MainMenu_PLCSettings {
            get {
                return ResourceManager.GetString("MainMenu_PLCSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Program ähnelt.
        /// </summary>
        public static string MainMenu_Program {
            get {
                return ResourceManager.GetString("MainMenu_Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reconnect To Client ähnelt.
        /// </summary>
        public static string MainMenu_ReconnectToClient {
            get {
                return ResourceManager.GetString("MainMenu_ReconnectToClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset All Sensors ähnelt.
        /// </summary>
        public static string MainMenu_ResetAllSensors {
            get {
                return ResourceManager.GetString("MainMenu_ResetAllSensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RPM-Meters Overview ähnelt.
        /// </summary>
        public static string MainMenu_RPMOverview {
            get {
                return ResourceManager.GetString("MainMenu_RPMOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sensor Settings ähnelt.
        /// </summary>
        public static string MainMenu_SensorSettings {
            get {
                return ResourceManager.GetString("MainMenu_SensorSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show/Hide Gui ähnelt.
        /// </summary>
        public static string MainMenu_ShowGui {
            get {
                return ResourceManager.GetString("MainMenu_ShowGui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show log file contents ähnelt.
        /// </summary>
        public static string MainMenu_ShowLog {
            get {
                return ResourceManager.GetString("MainMenu_ShowLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show MAC-Addresses of this computer ähnelt.
        /// </summary>
        public static string MainMenu_ShowMACs {
            get {
                return ResourceManager.GetString("MainMenu_ShowMACs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show SetupModel values ähnelt.
        /// </summary>
        public static string MainMenu_ShowSetupModel {
            get {
                return ResourceManager.GetString("MainMenu_ShowSetupModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show StatusModel values ähnelt.
        /// </summary>
        public static string MainMenu_ShowStatusModel {
            get {
                return ResourceManager.GetString("MainMenu_ShowStatusModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Switch chart style ähnelt.
        /// </summary>
        public static string MainMenu_SwitchChartStyle {
            get {
                return ResourceManager.GetString("MainMenu_SwitchChartStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Temperature Sensors Overview ähnelt.
        /// </summary>
        public static string MainMenu_TempOverview {
            get {
                return ResourceManager.GetString("MainMenu_TempOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable testmode ähnelt.
        /// </summary>
        public static string MainMenu_TestData {
            get {
                return ResourceManager.GetString("MainMenu_TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User Management ähnelt.
        /// </summary>
        public static string MainMenu_UserManagement {
            get {
                return ResourceManager.GetString("MainMenu_UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ZIP Data ähnelt.
        /// </summary>
        public static string MainMenu_ZIPData {
            get {
                return ResourceManager.GetString("MainMenu_ZIPData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure? ähnelt.
        /// </summary>
        public static string Messages_Question_Sure {
            get {
                return ResourceManager.GetString("Messages_Question_Sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start logging sensor data for ähnelt.
        /// </summary>
        public static string Messages_StartLog {
            get {
                return ResourceManager.GetString("Messages_StartLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die minutes now? ähnelt.
        /// </summary>
        public static string Messages_StartLog2 {
            get {
                return ResourceManager.GetString("Messages_StartLog2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Caution ähnelt.
        /// </summary>
        public static string Messages_Title_Caution {
            get {
                return ResourceManager.GetString("Messages_Title_Caution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string Messages_Title_Error {
            get {
                return ResourceManager.GetString("Messages_Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Info ähnelt.
        /// </summary>
        public static string Messages_Title_Info {
            get {
                return ResourceManager.GetString("Messages_Title_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Selection ähnelt.
        /// </summary>
        public static string NoSelection {
            get {
                return ResourceManager.GetString("NoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NPT-Time ähnelt.
        /// </summary>
        public static string NPT {
            get {
                return ResourceManager.GetString("NPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add an NPT-Server ähnelt.
        /// </summary>
        public static string NPT_Add {
            get {
                return ResourceManager.GetString("NPT_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove selected NPT-Server ähnelt.
        /// </summary>
        public static string NPT_Remove {
            get {
                return ResourceManager.GetString("NPT_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NPT server name ähnelt.
        /// </summary>
        public static string NPT_ServerName {
            get {
                return ResourceManager.GetString("NPT_ServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ok ähnelt.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PLC Settings ähnelt.
        /// </summary>
        public static string PLC {
            get {
                return ResourceManager.GetString("PLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Commission Standby Time [min] ähnelt.
        /// </summary>
        public static string PLC_CommissionStandbyTime {
            get {
                return ResourceManager.GetString("PLC_CommissionStandbyTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IEPE Max Digital Value [hex] ähnelt.
        /// </summary>
        public static string PLC_IEPEMaxDigitalValue {
            get {
                return ResourceManager.GetString("PLC_IEPEMaxDigitalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log duration when logging (mins) ähnelt.
        /// </summary>
        public static string PLC_LogRecordDurationMins {
            get {
                return ResourceManager.GetString("PLC_LogRecordDurationMins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Terminals / Channel ähnelt.
        /// </summary>
        public static string PLC_Terminals {
            get {
                return ResourceManager.GetString("PLC_Terminals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vibration Treshold ähnelt.
        /// </summary>
        public static string PLC_VibrationTreshold {
            get {
                return ResourceManager.GetString("PLC_VibrationTreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Measurment interval time (min) ähnelt.
        /// </summary>
        public static string PLC_VibrMeasLogPeriod {
            get {
                return ResourceManager.GetString("PLC_VibrMeasLogPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vibr Measurement Start Time ähnelt.
        /// </summary>
        public static string PLC_VibrMeasStartTime {
            get {
                return ResourceManager.GetString("PLC_VibrMeasStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Channel-ID ähnelt.
        /// </summary>
        public static string PLCTable_ChannelID {
            get {
                return ResourceManager.GetString("PLCTable_ChannelID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Channel Name ähnelt.
        /// </summary>
        public static string PLCTable_ChannelName {
            get {
                return ResourceManager.GetString("PLCTable_ChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IEPE-Value (0x) ähnelt.
        /// </summary>
        public static string PLCTable_IEPE {
            get {
                return ResourceManager.GetString("PLCTable_IEPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Terminal Name ähnelt.
        /// </summary>
        public static string PLCTable_TerminalName {
            get {
                return ResourceManager.GetString("PLCTable_TerminalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string PlcValuesTable_Name {
            get {
                return ResourceManager.GetString("PlcValuesTable_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value ähnelt.
        /// </summary>
        public static string PlcValuesTable_Value {
            get {
                return ResourceManager.GetString("PlcValuesTable_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reload ähnelt.
        /// </summary>
        public static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RPM-Meters ähnelt.
        /// </summary>
        public static string RPM {
            get {
                return ResourceManager.GetString("RPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Terminal name ähnelt.
        /// </summary>
        public static string RPM_Address {
            get {
                return ResourceManager.GetString("RPM_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RPM-meter name ähnelt.
        /// </summary>
        public static string RPM_Name {
            get {
                return ResourceManager.GetString("RPM_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number of increments ähnelt.
        /// </summary>
        public static string RPM_NoOfIncrements {
            get {
                return ResourceManager.GetString("RPM_NoOfIncrements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RPMs Overview ähnelt.
        /// </summary>
        public static string RPM_Overview {
            get {
                return ResourceManager.GetString("RPM_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sampling rate [kS] ähnelt.
        /// </summary>
        public static string RPM_SamplingRate {
            get {
                return ResourceManager.GetString("RPM_SamplingRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die X-Axis name ähnelt.
        /// </summary>
        public static string RPM_XAxis {
            get {
                return ResourceManager.GetString("RPM_XAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Y-Axis name ähnelt.
        /// </summary>
        public static string RPM_YAxis {
            get {
                return ResourceManager.GetString("RPM_YAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Address ähnelt.
        /// </summary>
        public static string RPMTable_Address {
            get {
                return ResourceManager.GetString("RPMTable_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RPM Name ähnelt.
        /// </summary>
        public static string RPMTable_Name {
            get {
                return ResourceManager.GetString("RPMTable_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number of Increments ähnelt.
        /// </summary>
        public static string RPMTable_NoOfIncrements {
            get {
                return ResourceManager.GetString("RPMTable_NoOfIncrements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sampling ähnelt.
        /// </summary>
        public static string RPMTable_Sampling {
            get {
                return ResourceManager.GetString("RPMTable_Sampling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die X-Axis ähnelt.
        /// </summary>
        public static string RPMTable_XAxis {
            get {
                return ResourceManager.GetString("RPMTable_XAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Y-Axis ähnelt.
        /// </summary>
        public static string RPMTable_YAxis {
            get {
                return ResourceManager.GetString("RPMTable_YAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save all ähnelt.
        /// </summary>
        public static string SaveAll {
            get {
                return ResourceManager.GetString("SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Graph ähnelt.
        /// </summary>
        public static string SensorMax_Graph {
            get {
                return ResourceManager.GetString("SensorMax_Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sensor Test ähnelt.
        /// </summary>
        public static string SensorTest {
            get {
                return ResourceManager.GetString("SensorTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Temperature sensors ähnelt.
        /// </summary>
        public static string Temp {
            get {
                return ResourceManager.GetString("Temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Terminal name ähnelt.
        /// </summary>
        public static string Temp_Address {
            get {
                return ResourceManager.GetString("Temp_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sensor name ähnelt.
        /// </summary>
        public static string Temp_Name {
            get {
                return ResourceManager.GetString("Temp_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Offset ähnelt.
        /// </summary>
        public static string Temp_Offset {
            get {
                return ResourceManager.GetString("Temp_Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Temperature sensors overview ähnelt.
        /// </summary>
        public static string Temp_Overview {
            get {
                return ResourceManager.GetString("Temp_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scale ähnelt.
        /// </summary>
        public static string Temp_Scale {
            get {
                return ResourceManager.GetString("Temp_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die X-Axis ähnelt.
        /// </summary>
        public static string Temp_XAxis {
            get {
                return ResourceManager.GetString("Temp_XAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Y-Axis ähnelt.
        /// </summary>
        public static string Temp_YAxis {
            get {
                return ResourceManager.GetString("Temp_YAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Terminal name ähnelt.
        /// </summary>
        public static string TempTable_Address {
            get {
                return ResourceManager.GetString("TempTable_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sensor name ähnelt.
        /// </summary>
        public static string TempTable_Name {
            get {
                return ResourceManager.GetString("TempTable_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Offset ähnelt.
        /// </summary>
        public static string TempTable_Offset {
            get {
                return ResourceManager.GetString("TempTable_Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scale ähnelt.
        /// </summary>
        public static string TempTable_Scale {
            get {
                return ResourceManager.GetString("TempTable_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die X-Axis ähnelt.
        /// </summary>
        public static string TempTable_XAxis {
            get {
                return ResourceManager.GetString("TempTable_XAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Y-Axis ähnelt.
        /// </summary>
        public static string TempTable_YAxis {
            get {
                return ResourceManager.GetString("TempTable_YAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About CMS@Wind ähnelt.
        /// </summary>
        public static string Tool_About {
            get {
                return ResourceManager.GetString("Tool_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Contact ähnelt.
        /// </summary>
        public static string Tool_Contact {
            get {
                return ResourceManager.GetString("Tool_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add new User ähnelt.
        /// </summary>
        public static string User_Add {
            get {
                return ResourceManager.GetString("User_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Username ähnelt.
        /// </summary>
        public static string User_Name {
            get {
                return ResourceManager.GetString("User_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        public static string User_Password {
            get {
                return ResourceManager.GetString("User_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove selected User ähnelt.
        /// </summary>
        public static string User_Remove {
            get {
                return ResourceManager.GetString("User_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Role ähnelt.
        /// </summary>
        public static string User_Role {
            get {
                return ResourceManager.GetString("User_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User Management ähnelt.
        /// </summary>
        public static string User_Title {
            get {
                return ResourceManager.GetString("User_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Username ähnelt.
        /// </summary>
        public static string UserTable_Name {
            get {
                return ResourceManager.GetString("UserTable_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Role ähnelt.
        /// </summary>
        public static string UserTable_Role {
            get {
                return ResourceManager.GetString("UserTable_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ZIP Data ähnelt.
        /// </summary>
        public static string ZIP_Data {
            get {
                return ResourceManager.GetString("ZIP_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Destination file path ähnelt.
        /// </summary>
        public static string ZIP_DestFilePath {
            get {
                return ResourceManager.GetString("ZIP_DestFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drag and drop directories and/or files to list: ähnelt.
        /// </summary>
        public static string ZIP_DragAndDropToList {
            get {
                return ResourceManager.GetString("ZIP_DragAndDropToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove selected ähnelt.
        /// </summary>
        public static string ZIP_RemoveSelected {
            get {
                return ResourceManager.GetString("ZIP_RemoveSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ZIP Data ähnelt.
        /// </summary>
        public static string ZIP_Title {
            get {
                return ResourceManager.GetString("ZIP_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zipping files ähnelt.
        /// </summary>
        public static string ZIP_ZippingFiles {
            get {
                return ResourceManager.GetString("ZIP_ZippingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Amount Files ähnelt.
        /// </summary>
        public static string ZIPTable_AmountFiles {
            get {
                return ResourceManager.GetString("ZIPTable_AmountFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File Size ähnelt.
        /// </summary>
        public static string ZIPTable_FileSize {
            get {
                return ResourceManager.GetString("ZIPTable_FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string ZIPTable_Name {
            get {
                return ResourceManager.GetString("ZIPTable_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Path ähnelt.
        /// </summary>
        public static string ZIPTable_Path {
            get {
                return ResourceManager.GetString("ZIPTable_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type ähnelt.
        /// </summary>
        public static string ZIPTable_Type {
            get {
                return ResourceManager.GetString("ZIPTable_Type", resourceCulture);
            }
        }
    }
}
