//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hashi.Gui.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hashi.Gui.Language.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rules will now be used to generate hints..
        /// </summary>
        public static string _0AllRules {
            get {
                return ResourceManager.GetString("_0AllRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Islands with a maximum of one bridge can set their connection if there is only one neighbor island accepting bridges. Neighbor islands with a maximum of one bridge cannot be connected to as both islands would be isolated then..
        /// </summary>
        public static string _1ConnectionRule1 {
            get {
                return ResourceManager.GetString("_1ConnectionRule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If an island with a maximum of two bridges has two neighbor islands with also a maximum of two bridges, then a connection to each neighbor must be set..
        /// </summary>
        public static string _2ConnectionsRule1 {
            get {
                return ResourceManager.GetString("_2ConnectionsRule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If an island with a maximum of two bridges has a connection to another island with max one connection, then the other connection can only go to a neighbor with max connections &gt; 1..
        /// </summary>
        public static string _2ConnectionsRule2 {
            get {
                return ResourceManager.GetString("_2ConnectionsRule2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If an island with a maximum of two connections has two neighbor islands and one of them is an island with a maximum of two connections, a connection must be established to the other island..
        /// </summary>
        public static string _2ConnectionsRule3 {
            get {
                return ResourceManager.GetString("_2ConnectionsRule3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If an island with a maximum of two bridges has a neighbor island with maximum bridges greater than one and all remaining neighbors are islands with a maximum of one bridge, a bridge must be drawn to the larger island..
        /// </summary>
        public static string _2ConnectionsRule4 {
            get {
                return ResourceManager.GetString("_2ConnectionsRule4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If an island with a maximum of three bridges has only two neighbors, then a connection must be set to each neighbor..
        /// </summary>
        public static string _3ConnectionsRule1 {
            get {
                return ResourceManager.GetString("_3ConnectionsRule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If an island with a maximum of three bridges has three neighbors, and one is a 1-connection and another a 2-connection island then a connection must be set to the remaining neighbor..
        /// </summary>
        public static string _3ConnectionsRule2 {
            get {
                return ResourceManager.GetString("_3ConnectionsRule2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Islands with a maximum of four bridges can set all connections if only two neighbors are available..
        /// </summary>
        public static string _4ConnectionsRule1 {
            get {
                return ResourceManager.GetString("_4ConnectionsRule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Islands with a maximum of four bridges and three neighbors can set one connection to each neighbor if one of the neighbors already has a connection to the island and has max connections..
        /// </summary>
        public static string _4ConnectionsRule2 {
            get {
                return ResourceManager.GetString("_4ConnectionsRule2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If an island with a maximum of five connections has three neighbors then each needs one connection..
        /// </summary>
        public static string _5ConnectionsRule1 {
            get {
                return ResourceManager.GetString("_5ConnectionsRule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If an island with a maximum of five  bridges has three neighbors and one connection to the source island only allows a maximum of one bridge, then the remaining connections for the source island can be set..
        /// </summary>
        public static string _5ConnectionsRule2 {
            get {
                return ResourceManager.GetString("_5ConnectionsRule2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If a 5-connection island has four neighbors and two full neighbors have a total of no more than two connections to the island, a connection must be drawn to each of the remaining neighbors if no connection has already been established..
        /// </summary>
        public static string _5ConnectionsRule3 {
            get {
                return ResourceManager.GetString("_5ConnectionsRule3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If an island with a maximum of six connections has three neighbors then set all connections..
        /// </summary>
        public static string _6ConnectionsRule1 {
            get {
                return ResourceManager.GetString("_6ConnectionsRule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If a 6-connection island has four neighbors and already has a 1-connection to one of these islands, which no longer allows further connections, then every other island must receive at least one connection..
        /// </summary>
        public static string _6ConnectionsRule2 {
            get {
                return ResourceManager.GetString("_6ConnectionsRule2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If an island with a maximum of six bridges has four neighbors and one neighbor has a maximum of one bridge, the remaining neighbors must each receive at least one connection..
        /// </summary>
        public static string _6ConnectionsRule3 {
            get {
                return ResourceManager.GetString("_6ConnectionsRule3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If an island with a maximum of seven connections has four neighbors then each needs one connection..
        /// </summary>
        public static string _7ConnectionsRule1 {
            get {
                return ResourceManager.GetString("_7ConnectionsRule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If an island with a maximum of seven bridges has four neighbors and one maxed-out neighbor accounts for only one connection, each remaining neighbor must receive two connections..
        /// </summary>
        public static string _7ConnectionsRule2 {
            get {
                return ResourceManager.GetString("_7ConnectionsRule2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If an island with a maximum of eight connections has four neighbors then set all connections..
        /// </summary>
        public static string _8ConnectionsRule1 {
            get {
                return ResourceManager.GetString("_8ConnectionsRule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Islands with only one active neighbor can set their remaining connections to that neighbor..
        /// </summary>
        public static string _9GeneralRule1 {
            get {
                return ResourceManager.GetString("_9GeneralRule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If setting a connection to any neighbor would result in a maxed-out island and maxed-out CONNECTED neighbors, check if the whole group is isolated. If it is, set the connection to the remaining neighbor..
        /// </summary>
        public static string _9GeneralRule2 {
            get {
                return ResourceManager.GetString("_9GeneralRule2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If an island&apos;s remaining connections equal twice the connectable neighbor count minus one, every connectable neighbor must receive at least one connection (pigeonhole principle)..
        /// </summary>
        public static string _9GeneralRule3 {
            get {
                return ResourceManager.GetString("_9GeneralRule3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If an island&apos;s remaining connections exactly equal twice the connectable neighbor count, every connectable neighbor must receive exactly two connections (maximum saturation)..
        /// </summary>
        public static string _9GeneralRule4 {
            get {
                return ResourceManager.GetString("_9GeneralRule4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If an island&apos;s remaining connections exactly equal the total capacity of all connectable neighbors (accounting for neighbors limited to one connection), every connectable neighbor must receive at least one connection (capacity-aware saturation)..
        /// </summary>
        public static string _9GeneralRule5 {
            get {
                return ResourceManager.GetString("_9GeneralRule5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If an island&apos;s remaining connections equal the total neighbor capacity minus one, every neighbor with at least two remaining connections must receive at least one connection (capacity-aware pigeonhole)..
        /// </summary>
        public static string _9GeneralRule6 {
            get {
                return ResourceManager.GetString("_9GeneralRule6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABORT.
        /// </summary>
        public static string DialogAbort {
            get {
                return ResourceManager.GetString("DialogAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIRM.
        /// </summary>
        public static string DialogConfirm {
            get {
                return ResourceManager.GetString("DialogConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        public static string DialogNo {
            get {
                return ResourceManager.GetString("DialogNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YES.
        /// </summary>
        public static string DialogYes {
            get {
                return ResourceManager.GetString("DialogYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hashiwokakero.
        /// </summary>
        public static string GameTitle {
            get {
                return ResourceManager.GetString("GameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Testmode.
        /// </summary>
        public static string GameTitleTestmodeSuffix {
            get {
                return ResourceManager.GetString("GameTitleTestmodeSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string MessageDeleteScenarioCaption {
            get {
                return ResourceManager.GetString("MessageDeleteScenarioCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to delete the scenario {0}. Continue?.
        /// </summary>
        public static string MessageDeleteScenarioText {
            get {
                return ResourceManager.GetString("MessageDeleteScenarioText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Over.
        /// </summary>
        public static string MessageGameOverCaption {
            get {
                return ResourceManager.GetString("MessageGameOverCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All connections are set! Your time: {0}.
        /// </summary>
        public static string MessageGameOverText {
            get {
                return ResourceManager.GetString("MessageGameOverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Careful.
        /// </summary>
        public static string MessageIsolatedGroupCaption {
            get {
                return ResourceManager.GetString("MessageIsolatedGroupCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have created an isolated group of islands. This results in an invalid bridge constellation. By the end of the game, all connections must be set and all islands must be connected..
        /// </summary>
        public static string MessageIsolatedGroupText {
            get {
                return ResourceManager.GetString("MessageIsolatedGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Highscore.
        /// </summary>
        public static string MessageNewHighscoreCaption {
            get {
                return ResourceManager.GetString("MessageNewHighscoreCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \n\nCongratulations! You have achieved a new high score for {0}.\n\nYour time: {1}\nPrevious high score: {2}.
        /// </summary>
        public static string MessageNewHighscoreText {
            get {
                return ResourceManager.GetString("MessageNewHighscoreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hints available.
        /// </summary>
        public static string MessageNoHintsCaption {
            get {
                return ResourceManager.GetString("MessageNoHintsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no hints available..
        /// </summary>
        public static string MessageNoHintsText {
            get {
                return ResourceManager.GetString("MessageNoHintsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caution.
        /// </summary>
        public static string MessageResetAllToDefaultCaption {
            get {
                return ResourceManager.GetString("MessageResetAllToDefaultCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to load all settings from default? Current settings will be lost..
        /// </summary>
        public static string MessageResetAllToDefaultText {
            get {
                return ResourceManager.GetString("MessageResetAllToDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait - generating Hashi puzzle....
        /// </summary>
        public static string TextHashiLoading {
            get {
                return ResourceManager.GetString("TextHashiLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint: .
        /// </summary>
        public static string TextHint {
            get {
                return ResourceManager.GetString("TextHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string TextTestfieldName {
            get {
                return ResourceManager.GetString("TextTestfieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE NEW GAME.
        /// </summary>
        public static string TitleCreate {
            get {
                return ResourceManager.GetString("TitleCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW TESTSCENARIO.
        /// </summary>
        public static string TitleCreateTestfield {
            get {
                return ResourceManager.GetString("TitleCreateTestfield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MESSAGES.
        /// </summary>
        public static string TitleMessages {
            get {
                return ResourceManager.GetString("TitleMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPTIONS.
        /// </summary>
        public static string TitleOptions {
            get {
                return ResourceManager.GetString("TitleOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USED RULE(S).
        /// </summary>
        public static string TitleRules {
            get {
                return ResourceManager.GetString("TitleRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TESTSCENARIOS.
        /// </summary>
        public static string TitleTestfields {
            get {
                return ResourceManager.GetString("TitleTestfields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMES.
        /// </summary>
        public static string TitleTimes {
            get {
                return ResourceManager.GetString("TitleTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new game.
        /// </summary>
        public static string TooltipCreate {
            get {
                return ResourceManager.GetString("TooltipCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new test scenario.
        /// </summary>
        public static string TooltipCreateTestfield {
            get {
                return ResourceManager.GetString("TooltipCreateTestfield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this testscenario.
        /// </summary>
        public static string TooltipDeleteTestfield {
            get {
                return ResourceManager.GetString("TooltipDeleteTestfield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected difficulty level.
        /// </summary>
        public static string TooltipDifficultyLevel {
            get {
                return ResourceManager.GetString("TooltipDifficultyLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string TooltipLanguage {
            get {
                return ResourceManager.GetString("TooltipLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string TooltipRedo {
            get {
                return ResourceManager.GetString("TooltipRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all bridges.
        /// </summary>
        public static string TooltipRemoveAllBridges {
            get {
                return ResourceManager.GetString("TooltipRemoveAllBridges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all settings to default.
        /// </summary>
        public static string TooltipResetAllSettingsToDefault {
            get {
                return ResourceManager.GetString("TooltipResetAllSettingsToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show hint.
        /// </summary>
        public static string TooltipShowHint {
            get {
                return ResourceManager.GetString("TooltipShowHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset this testscenario.
        /// </summary>
        public static string TooltipTestfieldReset {
            get {
                return ResourceManager.GetString("TooltipTestfieldReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save testfield for selected rule..
        /// </summary>
        public static string TooltipTestfieldSave {
            get {
                return ResourceManager.GetString("TooltipTestfieldSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testmode.
        /// </summary>
        public static string TooltipTestmode {
            get {
                return ResourceManager.GetString("TooltipTestmode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle gridlines.
        /// </summary>
        public static string TooltipToggleGridlines {
            get {
                return ResourceManager.GetString("TooltipToggleGridlines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string TooltipUndo {
            get {
                return ResourceManager.GetString("TooltipUndo", resourceCulture);
            }
        }
    }
}
